language: c
sudo: true
compiler: clang

matrix:
  include:
    # GNU/Linux tests #############################################
    - os: linux
      dist: xenial
      python: "3.6"
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
          packages:
            - libsdl2-dev
      before_install:
        - sudo add-apt-repository -y ppa:team-xbmc/ppa
        - sudo apt-get update -qq
        - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
        - sudo apt-get install -y libsdl2-dev
        - sudo apt-get install -y python3-pip python3-setuptools
        - sudo pip3 install -U pip
        - sudo pip3 install meson ninja
    - os: linux
      dist: xenial
      python: "3.6"
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:team-xbmc/ppa
        - sudo apt-get update -qq
        - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
        - sudo apt-get install -y libsdl2-dev
        - sudo apt-get install -y python3-pip python3-setuptools
        - sudo pip3 install --upgrade pip
        - sudo pip3 install meson ninja

    # OSX #######################################################
    - os: osx
      ruby: 2.3
      osx_image: xcode10.2
      before_install:
        - brew update && brew install sdl2 python
        - python -m pip install --upgrade pip
        - pip3 install meson ninja

script:
  - meson build
  - ninja -C build
  - cd build && sudo meson install
